import fs from 'node:fs';
import {randomUUID} from 'node:crypto';
import express from 'express';
import {createServer as createHttpServer} from 'node:http';
import {PGlite} from '@electric-sql/pglite';
import {createServer} from 'vite';
import {registerAdminRoutes} from '../../src/server/adminRoutes';
import {pastikanPaket} from '../../services/billing/store';
import {SAAS_PLANS} from '../../src/config/saasPlans';
import {ensureSubscription} from '../../services/billing/engine';
import type {Db} from '../../services/shared/db';
const pg=new PGlite(),subject=randomUUID(),owner=randomUUID(),tenant=randomUUID(),merchant=randomUUID(),outlet=randomUUID();
const wrap=(runner:any):Db=>({query:async(sql,params)=>{const r=await runner.query(sql,params);return{rows:r.rows,rowCount:r.rows.length||r.affectedRows||0};},exec:async s=>{await runner.exec(s);},tx:fn=>pg.transaction(c=>fn(wrap(c))),close:()=>pg.close()});
const db=wrap(pg);
await pg.exec('CREATE ROLE anon NOLOGIN;CREATE ROLE authenticated NOLOGIN;CREATE ROLE service_role NOLOGIN;');
for(const file of ['migrations/0001_compat.sql','schema.sql','schema_hybrid_pos.sql',...fs.readdirSync('migrations').filter(f=>/^\d{4}_.*\.sql$/.test(f)&&f!=='0001_compat.sql').sort().map(f=>'migrations/'+f)])await pg.exec(fs.readFileSync(file,'utf8'));
await db.query("INSERT INTO internal.internal_users(id,email,full_name,role,sso_subject) VALUES($1,'fixture-admin@localhost.invalid','Admin Fixture','ROLE_SUPERADMIN',$2)",[randomUUID(),subject]);
await db.query("INSERT INTO internal.tenants(id,name,owner_user_ref) VALUES($1,'Customer Fixture',$2)",[tenant,owner]);
await db.query("INSERT INTO internal.merchants(id,tenant_id,name,business_sector) VALUES($1,$2,'Laundry Fixture','LAUNDRY')",[merchant,tenant]);
await db.query("INSERT INTO internal.outlets(id,tenant_id,merchant_id,name) VALUES($1,$2,$3,'Outlet Utama')",[outlet,tenant,merchant]);
await pastikanPaket(db,SAAS_PLANS);await ensureSubscription(db,tenant);
const nativeFetch=globalThis.fetch;
globalThis.fetch=((input:any,init?:RequestInit)=>{const u=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url);if(!['127.0.0.1','localhost'].includes(u.hostname))throw Error('FIXTURE_REMOTE_FETCH_DENIED');return nativeFetch(input,init);}) as typeof fetch;
const app=express();app.use(express.json());
let resets=0;
registerAdminRoutes(app,async()=>db,async req=>req.headers.authorization==='Bearer fixture-admin'?{subject,aal:'aal2',mfaVerifiedAt:Math.floor(Date.now()/1000)}:null,{configured:true,ownerEmail:async id=>id===owner?'owner@localhost.invalid':null,sendReset:async()=>{resets++;}});
app.get('/__fixture/metrics',(_req,res)=>res.json({resets}));
app.use('/api',(_req,res)=>res.status(404).json({ok:false,error:'FIXTURE_NOT_IMPLEMENTED'}));
const server=createHttpServer(app);
const vite=await createServer({root:process.cwd(),envDir:'/private/tmp/newhope-fixture-no-env',define:{'import.meta.env.VITE_SUPABASE_URL':JSON.stringify(''),'import.meta.env.VITE_SUPABASE_ANON_KEY':JSON.stringify('')},server:{middlewareMode:true,hmr:{server},watch:null},appType:'custom'});
app.use(vite.middlewares);app.use(async(req,res,next)=>{if(req.method!=='GET')return next();try{res.type('html').send(await vite.transformIndexHtml(req.originalUrl,'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin support isolated fixture</title></head><body><div id="root"></div><script type="module" src="/scripts/dev/admin-support-fixture-entry.tsx"></script></body></html>'));}catch(e){next(e);}});
server.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));console.log('ADMIN_FIXTURE=http://127.0.0.1:'+(server.address() as any).port);
const stop=async()=>{await vite.close();await new Promise<void>(r=>server.close(()=>r()));await pg.close();process.exit(0);};process.once('SIGINT',()=>void stop());process.once('SIGTERM',()=>void stop());
