import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {SelectedStore} from '../../src/context/selectedStore';
import {guardedPath,legacyHashPath,moduleForPath,pathForModule,safeReturnPath,workspaceRoutes} from '../../src/lib/navigation/routes';
import {RefreshCoordinator,coalescedRead,setReadScope} from '../../src/lib/sync/refreshCoordinator';
import {kindsForModule} from '../../src/lib/sync/moduleKinds';
import {SharedStateSync} from '../../src/lib/sync/sharedState';
import {fetchRecentServerTransactions,fetchServerTransactions,fetchFinancialWorkspace} from '../../src/lib/reports/client';
import {resolveLegacyBusiness,businessForOutlet,type BusinessIdentity} from '../../src/lib/workspace/businessIdentity';
import {readBusinessDirectory} from '../../src/lib/workspace/businessDirectory';
import {checkoutDefaults,readCheckoutIntent,saveCheckoutIntent,claimCheckoutIntent,clearCheckoutIntent} from '../../src/lib/workspace/checkoutIntent';
import {verifiedSelection} from '../../src/lib/workspace/selection';
import {WorkspaceCache} from '../../src/lib/workspace/operationalCache';
import {addCartItem,discountCartItem,quantityCartItem,readCartDraft} from '../../src/lib/workspace/cart';
import {restoreAuthSession} from '../../src/lib/auth/sessionLifecycle';

let resolveInitial:(value:string|null)=>void=()=>{},authEvent:(value:string|null)=>void=()=>{},unsubscribed=false;
const authStates:Array<string|null>=[];
const stopAuth=restoreAuthSession(new Promise<string|null>(resolve=>{resolveInitial=resolve;}),receive=>{
  authEvent=receive;return()=>{unsubscribed=true;};
},session=>authStates.push(session),()=>{throw Error('Unexpected auth error');});
authEvent('owner-B');authEvent(null);resolveInitial('owner-A');await Promise.resolve();
assert.deepEqual(authStates,['owner-B',null],'Late stored session cannot restore account A after account switch/logout');
stopAuth();authEvent('owner-A');assert(unsubscribed);assert.deepEqual(authStates,['owner-B',null]);
let resolveUnmounted:(value:string)=>void=()=>{};
const stopUnmounted=restoreAuthSession(new Promise<string>(resolve=>{resolveUnmounted=resolve;}),()=>()=>{},()=>{throw Error('Unmounted auth changed state');},()=>{});
stopUnmounted();resolveUnmounted('old-account');await Promise.resolve();

const cartProduct={id:'cart-product',name:'Product',price:10000,costPrice:3000} as any;
const oneCart=addCartItem([],cartProduct),discountedCart=discountCartItem(oneCart,oneCart[0].id,10,0);
assert.equal(quantityCartItem(discountedCart,oneCart[0].id,3)[0].totalPrice,27000);
assert.equal(addCartItem(discountedCart,cartProduct)[0].totalPrice,18000,'Adding to discounted line recomputes proportional discount');
assert.equal(addCartItem(discountedCart,{...cartProduct,costPrice:9000})[0].unitCost,3000,'Existing cart HPP remains frozen');
assert.deepEqual(readCartDraft(JSON.stringify(oneCart)).items,JSON.parse(JSON.stringify(oneCart)),'Legacy array drafts are retained');
const completeDraft={version:2,items:oneCart,customer:{id:'customer'},table:{id:'table'},staff:{id:'staff'},orderType:'ONLINE'};
assert.deepEqual(readCartDraft(JSON.stringify(completeDraft)),JSON.parse(JSON.stringify(completeDraft)),'Selection context survives reload/switch');
assert.throws(()=>readCartDraft('{corrupt draft'),/JSON/);
assert.throws(()=>quantityCartItem(oneCart,oneCart[0].id,NaN),/INVALID_CART/);

for(const [module,path] of Object.entries(workspaceRoutes)){
  assert.equal(moduleForPath(path),module);assert.equal(pathForModule(module as any),path);
  assert.equal(guardedPath(path,false),'/login?returnTo='+encodeURIComponent(path));
  assert.equal(guardedPath('/login?returnTo='+encodeURIComponent(path),true),path);
  assert.equal(guardedPath(path,true),path,'Restoring authentication preserves deep links');
}
assert.equal(guardedPath('/register?returnTo=%2Freports',true),'/reports');
assert.equal(legacyHashPath('#login'),'/login');assert.equal(legacyHashPath('#payment'),'/subscription');
for(const unsafe of ['//other.invalid/pos','https://other.invalid/pos','/unknown'])assert.equal(safeReturnPath(unsafe),'/overview');
const store=new SelectedStore({cart:[],products:[],attendance:[],sync:0,reports:[],action:(n:number)=>n});
const catalog=store.select(['products']),cart=store.select(['cart']),reports=store.select(['reports']),action=store.select(['action']).action;
store.publish({...store.snapshot(),sync:1});assert.equal(store.select(['products']),catalog,'Sync does not invalidate catalog subscription');
store.publish({...store.snapshot(),attendance:[1] as any});assert.equal(store.select(['cart']),cart,'Attendance does not invalidate cart subscription');
store.publish({...store.snapshot(),cart:[1] as any,action:(n:number)=>n+1});
assert.equal(store.select(['reports']),reports,'Cart does not invalidate report subscription');
assert.equal(store.select(['action']).action,action);assert.equal(action(2),3,'Stable action calls the latest implementation');
assert(!kindsForModule('overview').includes('payroll_slips'));assert(!kindsForModule('pos').includes('attendance_logs'));
const business=(id:string,legacyAlias:string|null):BusinessIdentity=>({businessId:id,tenantId:'tenant',name:id,sector:'LAUNDRY',status:'ACTIVE',legacyAlias,outlets:[{outletId:id+'-outlet',businessId:id,name:'Outlet',address:'',status:'ACTIVE'}]});
const identities=[business('Laundry-A','owner_LAUNDRY'),business('Laundry-B',null)];
assert.equal(resolveLegacyBusiness('owner_LAUNDRY','tenant',identities)?.businessId,'Laundry-A');
assert.equal(resolveLegacyBusiness('missing_LAUNDRY','tenant',identities),null,'Sector alone cannot map an old queue');
assert.equal(resolveLegacyBusiness('owner_LAUNDRY','other-tenant',identities),null);
assert.equal(resolveLegacyBusiness('owner_LAUNDRY','tenant',[...identities,business('Duplicate','owner_LAUNDRY')]),null,'Ambiguous mappings are held');
assert.equal(businessForOutlet('Laundry-B-outlet','tenant',identities)?.businessId,'Laundry-B');
const selectable=identities.map(b=>({...b,transportRef:b.legacyAlias||'owner_business_'+b.businessId}));
assert.equal(verifiedSelection('owner','tenant',selectable,{businessId:'Laundry-B'})?.businessId,'Laundry-B');
assert.equal(verifiedSelection('owner','tenant',selectable,null,{sector:'LAUNDRY'})?.businessId,'Laundry-A','Only the exact alias maps a legacy preference');
assert.equal(verifiedSelection('owner','tenant',selectable,{businessId:'not-owned'}, {sector:'LAUNDRY'}),null,'Never fall back from a foreign/revoked preference');
assert.equal(verifiedSelection('owner','tenant',selectable,null),null,'Two same-sector businesses require selection, not sort order');
const severalOutlets=[{...selectable[1],outlets:[...selectable[1].outlets,{...selectable[1].outlets[0],outletId:'second'}]}];
assert.equal(verifiedSelection('owner','tenant',severalOutlets,{businessId:'Laundry-B'})?.outletId,undefined,'Multiple outlets require an explicit choice');
assert.equal(verifiedSelection('owner','tenant',severalOutlets,{businessId:'Laundry-B',outletId:'second'})?.outletId,'second');
const directoryTenant=randomUUID(),directoryIdentities=identities.map(original=>{const id=randomUUID();return {...original,tenantId:directoryTenant,businessId:id,outlets:[{...original.outlets[0],outletId:randomUUID(),businessId:id}]};});
assert.equal(readBusinessDirectory({ok:true,tenantId:directoryTenant,businesses:directoryIdentities}).businesses.length,2,'Same-sector businesses are never collapsed');
assert.throws(()=>readBusinessDirectory({ok:true,tenantId:randomUUID(),businesses:directoryIdentities}),/INVALID/);
assert.throws(()=>readBusinessDirectory({ok:true,tenantId:directoryTenant,businesses:[directoryIdentities[0],directoryIdentities[0]]}),/INVALID/);
assert.throws(()=>readBusinessDirectory({ok:true,tenantId:directoryTenant,businesses:[{...directoryIdentities[1],outlets:[directoryIdentities[0].outlets[0]]}]}),/INVALID/,'Outlet must have its exact business parent');
const paid={planId:'plan-plus-monthly',billingCycle:'YEARLY',extraOutlets:2} as any;
assert.deepEqual(checkoutDefaults('add-outlet',paid,true,'plan-free','MONTHLY'),{planId:'plan-plus-monthly',yearly:true,extraOutlets:3,onboarding:false});
assert.equal(checkoutDefaults('upgrade',paid,true,'plan-free',null).planId,'plan-pro-monthly');
assert.equal(checkoutDefaults(null,undefined,true,'plan-free',null).planId,'plan-plus-monthly','Used trials cannot be selected from stale onboarding hints');

const windowEvents=new EventTarget(),documentEvents=new EventTarget();
Object.defineProperty(globalThis,'window',{value:windowEvents,configurable:true});
Object.defineProperty(globalThis,'document',{value:Object.assign(documentEvents,{hidden:false}),configurable:true});
Object.defineProperty(globalThis,'navigator',{value:{onLine:true},configurable:true});
const pause=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const coordinator=new RefreshCoordinator();let runs=0,release:()=>void=()=>{};
const unsubscribe=coordinator.register('test',{interval:100000,run:async()=>{runs++;await new Promise<void>(resolve=>{release=resolve;});}});
await pause(15);assert.equal(runs,1);
window.dispatchEvent(new Event('focus'));document.dispatchEvent(new Event('visibilitychange'));
await pause(280);assert.equal(runs,1,'An in-flight resource cannot overlap after a focus burst');
release();await pause(15);
window.dispatchEvent(new Event('focus'));document.dispatchEvent(new Event('visibilitychange'));window.dispatchEvent(new Event('online'));
await pause(280);assert.equal(runs,2,'A focus/visibility/online burst produces one refresh');
release();await pause(15);document.hidden=true;window.dispatchEvent(new Event('focus'));await pause(280);
assert.equal(runs,2,'Hidden read jobs stay paused');unsubscribe();document.hidden=false;
const changes=new RefreshCoordinator();let sales=0,outlets=0,finishSales:()=>void=()=>{};
const offSales=changes.register('sales',{interval:100000,events:['financial-updated'],run:async()=>{sales++;await new Promise<void>(resolve=>{finishSales=resolve;});}});
const offOutlets=changes.register('outlets',{interval:100000,events:['outlets-updated'],run:async()=>{outlets++;}});
await pause(15);assert.equal(sales,1);assert.equal(outlets,1);
window.dispatchEvent(new Event('financial-updated'));window.dispatchEvent(new Event('outlets-updated'));
await pause(280);assert.equal(sales,1,'Domain invalidation cannot overlap the active request');assert.equal(outlets,2,'All event types survive the debounce, not just the final event');
finishSales();await pause(280);assert.equal(sales,2,'A mutation during a running snapshot schedules a follow-up read');
finishSales();offSales();offOutlets();await pause(15);
let reads=0,resolveRead:(value:number)=>void=()=>{};
const run=()=>{reads++;return new Promise<number>(resolve=>{resolveRead=resolve;});};
const abort=new AbortController(),readA=coalescedRead('same',run,abort.signal),readB=coalescedRead('same',run);
abort.abort();await assert.rejects(readA,/aborted/i);resolveRead(4);assert.equal(await readB,4);assert.equal(reads,1);
setReadScope('owner-A');let finishA:(value:string)=>void=()=>{};
const oldRead=coalescedRead('account-resource',()=>new Promise<string>(resolve=>{finishA=resolve;}));
setReadScope('owner-B');assert.equal(await coalescedRead('account-resource',async()=> 'B'),'B','A new account cannot share an old in-flight read');
finishA('A');assert.equal(await oldRead,'A');setReadScope('anonymous');

const disk=new Map<string,string>();
const sessionDisk=new Map<string,string>();
Object.defineProperty(globalThis,'sessionStorage',{value:{getItem:(key:string)=>sessionDisk.get(key)||null,setItem:(key:string,value:string)=>sessionDisk.set(key,value),removeItem:(key:string)=>sessionDisk.delete(key)},configurable:true});
Object.defineProperty(globalThis,'localStorage',{value:{getItem:(key:string)=>disk.get(key)||null,setItem:(key:string,value:string)=>disk.set(key,value)},configurable:true});
sessionDisk.set('nhpos_pending_checkout_plan','plan-pro-monthly');
disk.set('nhpos_pending_checkout_plan','plan-pro-monthly');
assert.equal(readCheckoutIntent('owner-A'),null,'Unowned old checkout hints cannot change an account flow');
saveCheckoutIntent(undefined,'plan-plus-monthly','YEARLY');claimCheckoutIntent('owner-A');
assert.equal(readCheckoutIntent('owner-A')?.cycle,'YEARLY');assert.equal(readCheckoutIntent(),null,'Guest intent is consumed once');
claimCheckoutIntent('owner-B');assert.equal(readCheckoutIntent('owner-B'),null,'Switching account never inherits the previous checkout');
saveCheckoutIntent('owner-B','plan-pro-monthly','MONTHLY');clearCheckoutIntent('owner-A');
assert.equal(readCheckoutIntent('owner-B')?.plan,'plan-pro-monthly','Clearing one account keeps the other account preference');
const expired=JSON.parse(sessionDisk.get('nhpos_checkout_intent_v2_owner-B')!);expired.expiresAt=Date.now()-1;
sessionDisk.set('nhpos_checkout_intent_v2_owner-B',JSON.stringify(expired));assert.equal(readCheckoutIntent('owner-B'),null);
assert.equal(disk.get('nhpos_pending_checkout_plan'),'plan-pro-monthly','Unknown legacy storage is ignored, not erased');
const cache=new WorkspaceCache('owner','LAUNDRY','owner_LAUNDRY');
const rosterOriginal=JSON.stringify([{id:'legacy-staff',businessId:'owner_LAUNDRY',name:'Staff'}]);
disk.set('newhope_user_owner_staff_members',rosterOriginal);
assert.deepEqual(cache.loadRoster(kindsForModule('overview')),[]);
cache.writeRoster([]);assert.equal(disk.get('newhope_user_owner_staff_members'),rosterOriginal,'Unused global roster is neither parsed nor replaced at startup');
assert.equal(cache.hydrateRoster()[0].id,'legacy-staff');
cache.writeRoster([]);assert.equal(disk.get('newhope_user_owner_staff_members'),'[]');
const corruptRoster=new WorkspaceCache('bad-roster','LAUNDRY','bad-roster_LAUNDRY');
disk.set('newhope_user_bad-roster_staff_members','{corrupt roster');
assert.throws(()=>corruptRoster.hydrateRoster());corruptRoster.writeRoster([]);
assert.equal(disk.get('newhope_user_bad-roster_staff_members'),'{corrupt roster','Malformed account source is not overwritten by fallback');
const payrollOriginal=JSON.stringify([{id:'old-payroll',amount:12000}]);disk.set(cache.key('payroll_slips'),payrollOriginal);
assert.deepEqual(cache.load('payroll_slips',[],kindsForModule('pos')),[]);
cache.write(cache.key('payroll_slips'),'[]');assert.equal(disk.get(cache.key('payroll_slips')),payrollOriginal,'Unloaded state cannot erase old browser data');
assert.equal(cache.load<any[]>('payroll_slips',[],kindsForModule('labor'))[0].id,'old-payroll');
cache.write(cache.key('payroll_slips'),'[]');assert.equal(disk.get(cache.key('payroll_slips')),'[]','A loaded operational collection can persist an explicit edit');
disk.set(cache.key('orders'),'ORIGINAL FINANCIAL BYTES');cache.write(cache.key('orders'),'[]');assert.equal(disk.get(cache.key('orders')),'ORIGINAL FINANCIAL BYTES','Financial cache cannot be overwritten before cloud hydration');
let gets=0,posts=0,status:any,lastKinds:string[]=[];
Object.defineProperty(globalThis,'fetch',{value:async(url:string,options:any)=>{
  if(options?.method==='POST'){posts++;const operations=JSON.parse(options.body).operations;
    return {ok:true,json:async()=>({ok:true,versions:operations.map((op:any)=>({kind:op.kind,recordId:op.recordId,revision:1}))})};}
  gets++;const kinds=new URL(url,'https://fixture.invalid').searchParams.get('kinds')!.split(',');
  return {ok:true,json:async()=>({ok:true,ready:true,scopeProof:true,kinds,records:[]})};
},configurable:true});
const sync=new SharedStateSync('module-owner','FNB',(_rows,_first,kinds)=>{lastKinds=kinds||[];},value=>{status=value;});
sync.setKinds(kindsForModule('overview'));sync.prime('products',[]);await sync.refresh(true);
sync.track('products',[{id:'local-product',name:'Safe cache',price:10,costPrice:1}]);assert.equal(status.pending,0,'Unloaded cache is not queued as a new edit');
assert.deepEqual(lastKinds,['store_settings','users']);
sync.setKinds(kindsForModule('inventory'));await sync.refresh(false);assert(lastKinds.includes('products'));
sync.importLegacy('products',[{id:'local-product',name:'Safe cache',price:10,costPrice:1}]);assert.equal(status.pending,1,'A later-opened collection can durably import its original cache');
sync.setKinds(kindsForModule('overview'));await sync.refresh(false);assert(lastKinds.includes('products'),'Pending kinds remain loaded even on an unrelated route');
assert.equal(status.pending,0);assert.equal(posts,1);assert.equal(gets,3);sync.stop();
const version='a'.repeat(32),versionsSent:Array<string|null>=[];let hydrationAttempts=0;
Object.defineProperty(globalThis,'fetch',{value:async(url:string)=>{
  const params=new URL(url,'https://fixture.invalid').searchParams;versionsSent.push(params.get('knownVersion'));
  return {ok:true,json:async()=>({ok:true,ready:true,version,kinds:['tables'],scopeProof:true,records:[]})};
},configurable:true});
const hydration=new SharedStateSync('hydrate-owner','FNB',(_rows,first)=>{
  hydrationAttempts++;assert.equal(first,hydrationAttempts<=2);if(hydrationAttempts===1)throw Error('CONSUMER_HYDRATION_FAILED');
},value=>{status=value;});
hydration.setKinds(['tables']);await hydration.refresh(true);assert.equal(status.ready,false);assert.equal(status.error,'CONSUMER_HYDRATION_FAILED');
await hydration.refresh(false);assert.equal(status.ready,true);assert.deepEqual(versionsSent,[null,null],'Failed hydration cannot send knownVersion and skip the next full snapshot');
await hydration.refresh(false);assert.equal(versionsSent[2],version,'Successful durable hydration can checkpoint its version');hydration.stop();
let reportRequests:string[]=[];
Object.defineProperty(globalThis,'fetch',{value:async(url:string)=>{
  reportRequests.push(url);const params=new URL(url,'https://fixture.invalid').searchParams;
  return {ok:true,json:async()=>({ok:true,transactions:[{serverId:params.get('cursor')||'first'}],nextCursor:params.get('cursor')?null:'page-2'})};
},configurable:true});
const query={sector:'FNB',outletId:'fixture-outlet'};
assert.equal((await fetchRecentServerTransactions(query)).length,1);assert.equal(reportRequests.length,1,'Automatic recent reads stop after one bounded page');
assert.equal(new URL(reportRequests[0],'https://fixture.invalid').searchParams.get('limit'),'100');
reportRequests=[];assert.equal((await fetchServerTransactions(query)).length,2);assert.equal(reportRequests.length,2,'Explicit export traverses cursor pages');
reportRequests=[];await fetchFinancialWorkspace(query,true);
assert.equal(reportRequests.length,2,'POS reads one recent page and one shift snapshot');
assert(reportRequests.some(path=>path.includes('/finance/shift?')));
assert(!reportRequests.some(path=>path.includes('/reports/summary')),'Opening POS never aggregates all-time reports');
reportRequests=[];await fetchFinancialWorkspace(query,false);
assert.equal(reportRequests.length,1,'Reports module owns its own summary/page; bootstrap reads only the shift');
const scopeA=randomUUID(),scopeB=randomUUID(),cloudRows=new Map<string,any[]>();let resolveOld:(data:any)=>void=()=>{},delayedA=true;
Object.defineProperty(globalThis,'fetch',{value:async(url:string,options:any)=>{
  if(options?.method==='POST'){
    const body=JSON.parse(options.body);cloudRows.set(body.businessId,body.operations.map((op:any)=>({scope:'LAUNDRY',...op,revision:1})));
    return {ok:true,json:async()=>({ok:true,versions:body.operations.map((op:any)=>({kind:op.kind,recordId:op.recordId,revision:1}))})};
  }
  const id=new URL(url,'https://fixture.invalid').searchParams.get('businessId');
  const data={ok:true,ready:true,scopeProof:true,business:{businessId:id,sector:'LAUNDRY',name:id},records:cloudRows.get(id!)||[]};
  if(id===scopeA&&delayedA){delayedA=false;return {ok:true,json:()=>new Promise(resolve=>{resolveOld=resolve;})};}
  return {ok:true,json:async()=>data};
},configurable:true});
let oldApplied=0;const newApplied:any[]=[];
const oldBusiness=new SharedStateSync('owner','LAUNDRY',()=>{oldApplied++;},()=>{}, {businessId:scopeA,transportRef:'owner_LAUNDRY'});
const oldHydration=oldBusiness.refresh(true);await pause(10);oldBusiness.stop();
const newBusiness=new SharedStateSync('owner','LAUNDRY',rows=>newApplied.push(rows),()=>{}, {businessId:scopeB,transportRef:'owner_business_B',namespace:scopeB});
newBusiness.prime('products',[]);await newBusiness.refresh(true);newBusiness.track('products',[{id:'prod-ld-12',name:'Second Laundry',price:100,costPrice:10,businessId:'owner_business_B',businessSector:'LAUNDRY'}]);
resolveOld({ok:true,ready:true,business:{businessId:scopeA,sector:'LAUNDRY'},records:[{scope:'LAUNDRY',kind:'products',recordId:'prod-ld-12',revision:1,deleted:false,value:{id:'prod-ld-12',name:'Wrong late data'}}]});await oldHydration;
assert.equal(oldApplied,0,'Switching same-sector businesses cancels late outgoing hydration');
assert(disk.has('newhope_shared_outbox_v3_owner_'+scopeB));
assert(!disk.get('newhope_shared_outbox_owner_LAUNDRY')?.includes('Second Laundry'),'Second business never writes its legacy sibling namespace');
newBusiness.stop();const reloaded=new SharedStateSync('owner','LAUNDRY',()=>{},value=>{status=value;},{businessId:scopeB,transportRef:'owner_business_B',namespace:scopeB});
assert.equal(status.pending,1,'Pending edits survive reload in their exact business namespace');await reloaded.refresh(true);assert.equal(status.pending,0);reloaded.stop();
assert.equal(cloudRows.get(scopeB)?.[0].value.name,'Second Laundry');assert(!cloudRows.has(scopeA));
console.log('PASS: deep-link guards, selective subscriptions, coordinated focus/hidden refresh, read dedupe, module hydration safety, bounded reports and explicit export');
console.log('PASS: canonical business/outlet selection, deferred cache preserves unloaded sources, same-sector in-flight switch and namespace-isolated reload');
