// Isolated synthetic DB + loopback HTTP. No provider tokens or production writes.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import express from 'express';
import { PGlite } from '@electric-sql/pglite';
import type { Db } from '../../services/shared/db';
import { createMcpHandler } from '../../src/server/mcpHandler';
import { hash, authorizationParams } from '../../services/mcp/routes';
import { runMcpTool, validateArguments } from '../../services/mcp/tools';

process.env.MCP_ENABLED = 'true';
process.env.MCP_PUBLIC_ORIGIN = 'https://kasir.newhope.space';
const origin = process.env.MCP_PUBLIC_ORIGIN;
const pg = new PGlite();
const wrap = (runner: any): Db => ({ query: async (sql, params) => { const r = await runner.query(sql, params); return { rows: r.rows, rowCount: r.affectedRows ?? r.rows.length }; }, exec: sql => runner.exec(sql), tx: fn => pg.transaction(tx => fn(wrap(tx))), close: () => pg.close() });
const db = wrap(pg);
let server: ReturnType<express.Express['listen']> | undefined;
try {
  await pg.exec('CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN; CREATE ROLE service_role NOLOGIN;');
  const migrations = ['migrations/0001_compat.sql','schema.sql','schema_hybrid_pos.sql', ...fs.readdirSync('migrations').filter(f => /^\d{4}_.*\.sql$/.test(f) && f !== '0001_compat.sql').sort().map(f => 'migrations/' + f)];
  for (const file of migrations) await pg.exec(fs.readFileSync(file,'utf8'));
  for (const file of ['free-plan-selection.sql','free-plan-ai-credit-access.sql','restrict-browser-rls-policies.sql','intelligence-cache.sql']) await pg.exec(fs.readFileSync('docs/security/' + file,'utf8'));
  await pg.exec(fs.readFileSync('supabase/migrations/20260928135919_mcp_readonly_connections.sql','utf8'));
  const tenant = randomUUID(), merchant = randomUUID(), product = randomUUID(), cashier = randomUUID(), sale = randomUUID();
  await db.query("INSERT INTO internal.tenants(id,name,owner_user_ref) VALUES($1,'Synthetic tenant','owner-a')", [tenant]);
  await db.query("INSERT INTO internal.merchants(id,tenant_id,name,business_sector,external_ref) VALUES($1,$2,'Synthetic shop','FNB','shop-a')", [merchant,tenant]);
  await db.query("INSERT INTO pos.tenants(id,name) VALUES($1,'Synthetic mirror')", [tenant]);
  await db.query("INSERT INTO pos.users(id,tenant_id,name,username,role,pin) VALUES($1,$2,'Private staff','synthetic','ADMIN','0000')", [cashier,tenant]);
  await db.query("INSERT INTO pos.products(id,tenant_id,merchant_id,name,sku,price,cost_price,business_sector) VALUES($1,$2,$3,'Coffee','TEST',10000,4000,'FNB')", [product,tenant,merchant]);
  await db.query("INSERT INTO pos.transactions(id,tenant_id,merchant_id,cashier_user_id,business_sector,subtotal,total_amount,payment_method,payment_status,order_status,created_at) VALUES($1,$2,$3,$4,'FNB',10000,11000,'CASH','PAID','COMPLETED','2026-09-20T01:00:00Z')", [sale,tenant,merchant,cashier]);
  await assert.rejects(() => runMcpTool(db,'owner-b','shop-a','business_info',{}), /BUSINESS_ACCESS_DENIED/);
  assert.throws(() => validateArguments('list_products',{ business_id: 'other' }), /INVALID/);
  assert.throws(() => validateArguments('list_products',{ offset: -1 }), /INVALID/);
  assert.throws(() => validateArguments('sales_summary',{ start: '2020-01-01T00:00:00Z',end:'2026-01-01T00:00:00Z' }), /INVALID/);
  const handler = createMcpHandler(async () => db, async req => req.headers.authorization === 'Bearer owner-session' ? { subject: 'owner-a' } : req.headers.authorization === 'Bearer other-session' ? { subject: 'owner-b' } : null);
  const app = express(); app.use((req,res) => void handler(req,res));
  server = app.listen(0,'127.0.0.1');
  await new Promise<void>(resolve => server!.once('listening', resolve));
  const address = server.address() as { port: number }, base = `http://127.0.0.1:${address.port}`;
  async function call(path: string, body?: any, token?: string, asForm = false, requestOrigin = origin) {
    const response = await fetch(base + path, { method: body === undefined ? 'GET' : 'POST', redirect:'manual', headers: { Origin: requestOrigin, ...(body === undefined ? {} : { 'Content-Type': asForm ? 'application/x-www-form-urlencoded' : 'application/json' }), ...(token ? { Authorization: 'Bearer ' + token } : {}) }, body: body === undefined ? undefined : asForm ? new URLSearchParams(body).toString() : JSON.stringify(body) });
    const text = await response.text(); return { status: response.status, headers: response.headers, body: text ? JSON.parse(text) : null };
  }
  assert.equal((await call('/api/mcp')).status,401);
  assert.match((await call('/api/mcp')).headers.get('www-authenticate')!,/oauth-protected-resource/);
  const metadata = await call('/.well-known/oauth-authorization-server');
  assert.deepEqual(metadata.body.code_challenge_methods_supported,['S256']);
  assert.equal((await call('/.well-known/oauth-protected-resource')).body.resource,origin+'/api/mcp');
  assert.equal((await call('/api/mcp/register',{ redirect_uris:['https://evil.example/callback'] })).status,400);
  const registered = await call('/api/mcp/register',{ redirect_uris:['https://claude.ai/api/mcp/auth_callback'], token_endpoint_auth_method:'none' });
  assert.equal(registered.status,201); assert.equal(registered.body.client_id,'claude');
  assert.equal((await call('/api/mcp/register',{redirect_uris:['https://chatgpt.com/connector_platform_oauth_redirect'],token_endpoint_auth_method:'none'})).body.client_id,'chatgpt');
  const verifier = 'a'.repeat(64), challenge = createHash('sha256').update(verifier).digest('base64url');
  const args = { client_id:'claude', redirect_uri:'https://claude.ai/api/mcp/auth_callback', response_type:'code', code_challenge_method:'S256', code_challenge:challenge, resource:origin+'/api/mcp', scope:'pos:read', state:'state-check' };
  assert.throws(() => authorizationParams({ ...args, redirect_uri:'https://evil.example' }),/invalid_client/);
  assert.throws(() => authorizationParams({ ...args, resource:'https://evil.example' }),/invalid_target/);
  assert.throws(() => authorizationParams({ ...args, scope:'pos:write' }),/invalid_scope/);
  const badConsent = await call('/api/mcp/consent',{...args,business_id:'shop-a',approve:true},'other-session'); assert.equal(badConsent.status,400);
  assert.equal((await call('/api/mcp/consent',{...args,business_id:'shop-a',approve:true},'owner-session',false,'https://evil.example')).status,403);
  const denial = await call('/api/mcp/consent',{...args,approve:false},'owner-session');
  assert.equal(new URL(denial.body.redirect).searchParams.get('error'),'access_denied');
  const consent = await call('/api/mcp/consent',{...args,business_id:'shop-a',approve:true},'owner-session');
  assert.equal(consent.status,200);
  const redirect = new URL(consent.body.redirect), code = redirect.searchParams.get('code');
  assert.equal(redirect.searchParams.get('iss'),origin); assert.equal(redirect.searchParams.get('state'),'state-check');
  const exchange = { client_id:'claude', grant_type:'authorization_code', code, code_verifier:verifier, redirect_uri:args.redirect_uri, resource:args.resource };
  assert.equal((await call('/api/mcp/token',{...exchange,code_verifier:'b'.repeat(64)},undefined,true)).status,400);
  assert.equal((await call('/api/mcp/token',{...exchange,redirect_uri:'https://evil.example'},undefined,true)).status,400);
  const tokens = await call('/api/mcp/token',exchange,undefined,true); assert.equal(tokens.status,200);
  const rpc = (method: string, params?: any) => ({ jsonrpc:'2.0', id:1, method, params });
  const access = tokens.body.access_token;
  assert.equal((await call('/api/mcp',rpc('initialize',{protocolVersion:'2025-06-18'}),access)).body.result.protocolVersion,'2025-06-18');
  assert.equal((await call('/api/mcp',rpc('tools/list'),access)).body.result.tools.length,5);
  assert.equal((await call('/api/mcp',{jsonrpc:'2.0',method:'notifications/initialized'},access)).status,202);
  assert.equal((await call('/api/mcp',rpc('tools/list'),'owner-session')).status,401);
  const toolsCall = (name: string, a = {}) => call('/api/mcp',rpc('tools/call',{name,arguments:a}),access);
  const products = await toolsCall('list_products'); assert.equal(products.body.result.structuredContent.items[0].name,'Coffee');
  assert.equal('cost_price' in products.body.result.structuredContent.items[0],false);
  assert.equal(products.body.result.structuredContent.items[0].stock,null,'untracked inventory must not be invented as zero');
  assert.equal((await toolsCall('low_stock')).body.result.structuredContent.items.length,0);
  const dates = { start:'2026-09-20T00:00:00Z',end:'2026-09-21T00:00:00Z' };
  assert.equal(Number((await toolsCall('sales_summary',dates)).body.result.structuredContent.gross_collected_idr),11000);
  const transactions = await toolsCall('list_transactions',dates); assert.equal(transactions.body.result.structuredContent.items[0].id,sale);
  assert.equal(JSON.stringify(transactions.body).includes('Private staff'),false);
  assert.equal((await toolsCall('list_products',{business_id:'other'})).body.result.isError,true);
  assert.equal((await toolsCall('delete_transaction')).body.error.code,-32602);
  await db.query('UPDATE internal.tenants SET owner_user_ref=$2 WHERE id=$1',[tenant,'owner-b']);
  assert.equal((await toolsCall('business_info')).body.result.isError,true,'ownership changes invalidate data access');
  await db.query('UPDATE internal.tenants SET owner_user_ref=$2 WHERE id=$1',[tenant,'owner-a']);
  const connections = await call('/api/mcp/manage',undefined,'owner-session'); assert.equal(connections.body.connections.length,1);
  assert.equal((await call('/api/mcp/manage',undefined,'other-session')).body.connections.length,0);
  const id = connections.body.connections[0].id;
  await call('/api/mcp/disconnect',{id},'other-session'); assert.equal((await toolsCall('business_info')).body.result.isError,false);
  // Expired trial blocks existing MCP tokens immediately without deleting data.
  await db.query("UPDATE internal.tenants SET created_at=now()-interval '60 days' WHERE id=$1",[tenant]);
  assert.equal((await toolsCall('business_info')).body.result.isError,true);
  await db.query('UPDATE internal.tenants SET created_at=now() WHERE id=$1',[tenant]);
  await db.query("UPDATE mcp_private.connections SET rate_count=60,rate_window=now() WHERE id=$1",[id]);
  assert.equal((await toolsCall('business_info')).status,429);
  await db.query("UPDATE mcp_private.connections SET rate_window=now()-interval '2 minutes' WHERE id=$1",[id]);
  const refresh = { client_id:'claude', grant_type:'refresh_token', refresh_token:tokens.body.refresh_token, resource:args.resource };
  const refreshed = await call('/api/mcp/token',refresh,undefined,true); assert.equal(refreshed.status,200);
  assert.notEqual(refreshed.body.refresh_token,tokens.body.refresh_token);
  assert.equal((await call('/api/mcp/token',refresh,undefined,true)).status,400);
  assert.equal((await call('/api/mcp',rpc('tools/list'),refreshed.body.access_token)).status,401,'refresh replay revokes entire connection');
  const consent2 = await call('/api/mcp/consent',{...args,business_id:'shop-a',approve:true},'owner-session');
  const code2 = new URL(consent2.body.redirect).searchParams.get('code');
  const tokens2 = await call('/api/mcp/token',{...exchange,code:code2},undefined,true);
  assert.equal(tokens2.status,200);
  const id2 = (await db.query('SELECT connection_id FROM mcp_private.credentials WHERE hash=$1',[hash(tokens2.body.access_token)])).rows[0].connection_id;
  await db.query("UPDATE mcp_private.credentials SET expires_at=now()-interval '1 second' WHERE hash=$1",[hash(tokens2.body.access_token)]);
  assert.equal((await call('/api/mcp',rpc('tools/list'),tokens2.body.access_token)).status,401,'expired access token denied');
  await db.query("UPDATE mcp_private.credentials SET expires_at=now()+interval '1 hour' WHERE hash=$1",[hash(tokens2.body.access_token)]);
  await call('/api/mcp/disconnect',{id:id2},'owner-session');
  assert.equal((await call('/api/mcp',rpc('tools/list'),tokens2.body.access_token)).status,401);
  const stored = (await db.query('SELECT hash FROM mcp_private.credentials')).rows;
  assert.ok(stored.every(r => /^[a-f0-9]{64}$/.test(r.hash)));
  const browserAccess = (await db.query("SELECT has_schema_privilege('authenticated','mcp_private','USAGE') AS allowed")).rows[0];
  assert.equal(browserAccess.allowed,false);
  await pg.exec('SET ROLE authenticated');
  await assert.rejects(() => db.query('SELECT * FROM mcp_private.connections'),/permission denied/);
  await pg.exec('RESET ROLE');
  process.env.MCP_ENABLED='false'; assert.equal((await call('/api/mcp')).status,503);
  console.log('MCP PASS: HTTP discovery/handshake/tools, PKCE, scoped consent, cross-owner denial, redaction, trial expiry, rate limit, refresh rotation/replay, revocation, hashed storage, private schema, kill switch.');
} finally { if (server) await new Promise<void>(resolve => server!.close(() => resolve())); await pg.close(); }
