// Isolated database only: no env, network, credentials or production writes.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
import { loadMerchantSnapshot } from '../../services/ai/snapshotData';
import { reportAggregates } from '../../src/lib/assistant/reportAggregates';
import type { Db } from '../../services/shared/db';
import { ambilDompet, pakaiKredit, kembalikanKredit, catatAudit, ringkasanAudit } from '../../services/ai/wallet';
import { registerAssistantRoutes } from '../../services/ai/routes';
import { paidContext, PAID_DATA_CONSENT } from '../../services/ai/paidPrivacy';
import { createAssistantHandler } from '../../src/server/assistantHandler';
import { ensureSubscription } from '../../services/billing/engine';

const pg=new PGlite();
const wrap=(runner:any):Db=>({query:async(sql,params)=>{const r=await runner.query(sql,params);return {rows:r.rows,rowCount:r.rows.length};},exec:sql=>runner.exec(sql),tx:fn=>pg.transaction(tx=>fn(wrap(tx))),close:()=>pg.close()});
const db=wrap(pg);
try {
  await pg.exec('CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN; CREATE ROLE service_role NOLOGIN;');
  const files=['migrations/0001_compat.sql','schema.sql','schema_hybrid_pos.sql',...fs.readdirSync('migrations').filter(f=>/^\d{4}_.*\.sql$/.test(f)&&f!=='0001_compat.sql').sort().map(f=>'migrations/'+f)];
  for(const file of files)await pg.exec(fs.readFileSync(file,'utf8'));
  await db.query("INSERT INTO billing.plans(id,name,price_idr) VALUES('plan-free','Trial test',0) ON CONFLICT DO NOTHING");
  for(const file of ['free-plan-selection.sql','free-plan-ai-credit-access.sql','restrict-browser-rls-policies.sql','intelligence-cache.sql','intelligence-wallet.sql'])await pg.exec(fs.readFileSync('docs/security/'+file,'utf8'));
  // Repeat reviewed SQL: reruns must not erase balances or create duplicate FKs.
  await pg.exec(fs.readFileSync('docs/security/intelligence-wallet.sql','utf8'));
  const tenant=randomUUID(), merchant=randomUUID();
  await db.query(`INSERT INTO internal.tenants(id,name,owner_user_ref) VALUES($1,'Intelligence test','brain-owner')`,[tenant]);
  await db.query(`INSERT INTO internal.merchants(id,tenant_id,name,business_sector,external_ref) VALUES($1,$2,'Test brain','FNB','brain-test')`,[merchant,tenant]);
  await assert.rejects(()=>loadMerchantSnapshot(db,{subject:'other-owner'},'brain-test'),/BUSINESS_NOT_OWNED/);
  await assert.rejects(()=>loadMerchantSnapshot(db,{subject:'local-development'},'brain-test'),/AUTHENTICATION_REQUIRED/);
  const snapshot=await loadMerchantSnapshot(db,{subject:'brain-owner'},'brain-test');
  await db.exec('SET ROLE svc_ai');
  await loadMerchantSnapshot(db,{subject:'brain-owner'},'brain-test');
  await db.exec('RESET ROLE');
  assert.equal(snapshot.orders.length,0); assert.equal(snapshot.products.length,0);
  const report=reportAggregates(snapshot,{period:'MONTH'});
  assert.equal(report.revenueTotal,0);assert.equal(report.ordersAnalysed,0);
  assert.equal('orders' in report,false); assert.equal('customers' in report,false);
  // Non-empty adapter fixture catches renamed/dropped catalog columns.
  const product=randomUUID(),cashier=randomUUID(),sale=randomUUID();
  await db.query("INSERT INTO pos.tenants(id,name) VALUES($1,'Test mirror')",[tenant]);
  await db.query("INSERT INTO pos.users(id,tenant_id,name,username,role,pin) VALUES($1,$2,'Synthetic cashier','synthetic-cashier','ADMIN','0000')",[cashier,tenant]);
  await db.query("INSERT INTO pos.products(id,tenant_id,merchant_id,name,sku,price,cost_price,business_sector) VALUES($1,$2,$3,'Synthetic product','TEST',10000,4000,'FNB')",[product,tenant,merchant]);
  await db.query("INSERT INTO pos.transactions(id,tenant_id,merchant_id,cashier_user_id,business_sector,subtotal,total_amount,payment_method,payment_status,order_status,created_at) VALUES($1,$2,$3,$4,'FNB',10000,10000,'CASH','PAID','COMPLETED',now()-interval '1 hour')",[sale,tenant,merchant,cashier]);
  await db.query("INSERT INTO pos.transaction_items(id,transaction_id,tenant_id,product_id,business_sector,product_name,unit_price,unit_cost,quantity,total_price) VALUES($1,$2,$3,$4,'FNB','Synthetic product',10000,4000,1,10000)",[randomUUID(),sale,tenant,product]);
  const populated=await loadMerchantSnapshot(db,{subject:'brain-owner'},'brain-test');
  assert.equal(populated.products[0].id,product);
  const populatedReport=reportAggregates(populated,{period:'LAST_30'});
  assert.equal(populatedReport.revenueTotal,10000);assert.equal(populatedReport.cogs,4000);assert.equal(populatedReport.grossMarginPct,60);
  const otherTenant=randomUUID(), secondTenant=randomUUID();
  await db.query("INSERT INTO internal.tenants(id,name,owner_user_ref) VALUES($1,'Other','other-owner'),($2,'Second','brain-owner')",[otherTenant,secondTenant]);
  await db.query("INSERT INTO internal.merchants(id,tenant_id,name,business_sector,external_ref) VALUES($1,$2,'Second','FNB','second-business'),($3,$4,'Other','FNB','other-business')",[randomUUID(),secondTenant,randomUUID(),otherTenant]);
  const wallet=await ambilDompet(db,'brain-owner','brain-test');
  assert.equal(wallet.balance,30);
  assert.equal((await ambilDompet(db,'brain-owner','second-business')).merchantId,wallet.merchantId);
  await assert.rejects(()=>ambilDompet(db,otherTenant,'brain-test'),/BUSINESS_NOT_OWNED/);
  await assert.rejects(()=>ambilDompet(db,'brain-owner','other-business'),/BUSINESS_NOT_OWNED/);
  await catatAudit(db,{merchantId:'brain-owner',businessId:'brain-test',query:'test',intent:'UNKNOWN',source:'RULE_ENGINE',creditsCharged:0,latencyMs:1});
  assert.equal((await db.query('SELECT count(*)::int AS n FROM ai.ai_query_logs WHERE merchant_id=$1',[wallet.merchantId])).rows[0].n,1);
  const consumed=await Promise.all(Array.from({length:35},()=>pakaiKredit(db,'brain-owner','second-business')));
  assert.equal(consumed.filter(Boolean).length,30);
  assert.equal((await ambilDompet(db,'brain-owner','brain-test')).balance,0);
  await kembalikanKredit(db,'brain-owner','brain-test',wallet.periodResetAt);
  assert.equal((await ambilDompet(db,'brain-owner','second-business')).balance,1);
  assert.equal((await db.query('SELECT difference FROM ai.credit_ledger_reconciliation WHERE merchant_id=$1',[wallet.merchantId])).rows[0].difference,0);
  const callbacks=new Map<string,any>();
  registerAssistantRoutes({get:(path:string,fn:any)=>callbacks.set('GET '+path,fn),post:(path:string,fn:any)=>callbacks.set('POST '+path,fn)} as any,db);
  const call=async(method:string,path:string,body:any={},subject='brain-owner',query:any={})=>{
    let code=200,payload:any;
    const res:any={status:(n:number)=>{code=n;return res;},json:(data:any)=>{payload=data;return res;},setHeader:()=>{}};
    await callbacks.get(method+' '+path)({body,query,headers:{'x-auth-sub':subject}},res,(err:any)=>{throw err;});
    return {code,payload};
  };
  const safeBody={query:'Apa strategi yang paling tepat?',merchantId:otherTenant,storeContext:{businessId:'brain-test',storeName:'PRIVATE_STORE'},allowLlm:true,paidDataConsent:PAID_DATA_CONSENT,insights:[{summary:'PRIVATE_CUSTOMER'}]};
  const mixed=await call('POST','/api/v1/assistant/query',{...safeBody,allowLlm:false,intent:'GET_INSIGHT_DIGEST',insights:[{title:'Device finding',summary:'Device data',metricLabel:'local',priority:1}]});
  assert.equal(mixed.payload.dataSource,'MIXED');assert.equal(mixed.payload.provenance.insights,'CLIENT');
  const table=await call('POST','/api/v1/assistant/query',{...safeBody,allowLlm:false,intent:'GET_TABLE_STATUS',insights:[],aggregates:{slotsTotal:10,slotsOccupied:2}});
  assert.equal(table.payload.dataSource,'MIXED');assert.equal(table.payload.provenance.slotsTotal,'CLIENT');
  const central=await call('POST','/api/v1/assistant/query',{...safeBody,allowLlm:false,intent:'GET_REVENUE_SUMMARY',insights:[]});
  assert.equal(central.payload.dataSource,'DATABASE');
  const originalFetch=globalThis.fetch;
  let providerCalls=0, wire='';
  process.env.DEEPSEEK_API_KEY='test-only-no-real-key';
  globalThis.fetch=async(_url:any,init:any)=>{providerCalls++;wire=String(init.body);return new Response(JSON.stringify({choices:[{message:{content:'Draft aman, perlu tinjauan owner.'}}],usage:{prompt_tokens:100,completion_tokens:20}}),{status:200,headers:{'Content-Type':'application/json'}});};
  try {
    assert.equal((await call('POST','/api/v1/assistant/query',{...safeBody,paidDataConsent:undefined})).payload.answer.costCredits,0);
    assert.equal(providerCalls,0);
    const answer=await call('POST','/api/v1/assistant/query',{...safeBody,purpose:'ACTION_PLAN'});
    assert.equal(answer.code,200);assert.equal(answer.payload.answer.costCredits,1);assert.equal(answer.payload.credits.balance,0);
    assert.equal(providerCalls,1);
    for(const secret of ['PRIVATE_STORE','PRIVATE_CUSTOMER',otherTenant,'brain-owner'])assert.ok(!wire.includes(secret));
    assert.ok(!wire.includes('Synthetic product')&&!wire.includes('Synthetic cashier')&&!wire.includes(sale));
    assert.ok(wire.includes(paidContext('brain-owner',report).member));
    await call('POST','/api/v1/assistant/query',safeBody);
    assert.equal(providerCalls,1,'exhausted member cannot call model');
    assert.equal((await call('POST','/api/v1/assistant/query',safeBody,'other-owner')).code,403);
    assert.equal((await call('POST','/api/v1/assistant/query',{...safeBody,query:{}})).code,400);
    await kembalikanKredit(db,'brain-owner','brain-test',wallet.periodResetAt);
    globalThis.fetch=async()=>{throw new Error('simulated provider outage');};
    const failed=await call('POST','/api/v1/assistant/query',safeBody);
    assert.equal(failed.payload.answer.source,'ERROR');
    assert.equal((await ambilDompet(db,'brain-owner','brain-test')).balance,1,'failed model refunds credit');
    await catatAudit(db,{merchantId:'brain-owner',businessId:'second-business',query:'Other unit question',intent:'UNKNOWN',source:'RULE_ENGINE',creditsCharged:0,latencyMs:1});
    const scopedAudit=await ringkasanAudit(db,'brain-owner',100,'brain-test');
    assert.ok(!scopedAudit.logs.some((row:any)=>row.query_text==='Other unit question'));
    const nextPeriod=new Date(Date.parse(wallet.periodResetAt)+40*86400000).toISOString();
    await db.query('UPDATE ai.merchant_ai_credits SET period_reset_at=$2,balance=30,used_this_month=0 WHERE merchant_id=$1',[wallet.merchantId,nextPeriod]);
    await kembalikanKredit(db,'brain-owner','brain-test',wallet.periodResetAt);
    assert.equal((await ambilDompet(db,'brain-owner','brain-test')).balance,30,'old-period refund cannot inflate new grant');
    // Preserve ambiguous legacy wallets but do not take away the zero-token path.
    await db.query('INSERT INTO ai.merchant_ai_credits(merchant_id,tenant_id,balance,monthly_grant,used_this_month,period_reset_at) VALUES($1,$1,5,30,25,$2)',[secondTenant,nextPeriod]);
    const deterministic=await call('POST','/api/v1/assistant/query',{...safeBody,query:'omzet hari ini',allowLlm:false});
    assert.equal(deterministic.payload.answer.costCredits,0);
    assert.equal(deterministic.payload.answer.source,'RULE_ENGINE');
    assert.equal((await call('POST','/api/v1/assistant/query',safeBody)).payload.answer.title,'Dompet perlu diperiksa');
    assert.equal((await db.query('SELECT balance FROM ai.merchant_ai_credits WHERE merchant_id=$1',[secondTenant])).rows[0].balance,5);
    // Expired 45-day trial must deny AI before wallet/model.
    await ensureSubscription(db,tenant);
    await db.query("UPDATE billing.subscriptions SET status='TRIAL',current_period_end=now()-interval '1 day' WHERE tenant_id=$1",[tenant]);
    assert.equal((await call('POST','/api/v1/assistant/query',safeBody)).code,403);
  } finally {globalThis.fetch=originalFetch;delete process.env.DEEPSEEK_API_KEY;}
  let code=0;const authRes:any={setHeader:()=>{},status:(n:number)=>{code=n;return authRes;},json:()=>{}};
  await createAssistantHandler(async()=>null,async()=>{throw new Error('must not connect');})({url:'/api/v1/assistant/query',method:'POST',headers:{'x-auth-sub':'brain-owner'}},authRes);
  assert.equal(code,401,'forged principal header is not authentication');
  assert.equal((await db.query("SELECT has_table_privilege('authenticated','ai.business_intelligence_cache','SELECT') AS allowed")).rows[0].allowed,false);
  assert.equal((await db.query("SELECT has_table_privilege('authenticated','contract.intelligence_catalog','SELECT') AS allowed")).rows[0].allowed,false);
  console.log('PASS: member wallet isolation/shared quota, atomic exhaustion, refund ledger, consent, real route payload privacy, free expiry, forged-header denial, private cache');
  console.log('PASS: full migrated schema loader, owner isolation enforced inside loader, no raw rows in report contract');
} catch(error) { console.error(error);process.exitCode=1; } finally {await pg.close();}
