import assert from 'node:assert/strict';
import { buildBusinessBrain, forecastDemand, simulatePrice, nextBestOffers } from '../../src/lib/assistant/businessBrain';
import { parsePeriod, reportWindow, businessDate, addDate, DAY, dayStart } from '../../src/lib/assistant/periods';
import { reportAggregates } from '../../src/lib/assistant/reportAggregates';
import { ensureDailyInsights } from '../../src/lib/assistant/scheduler';
import { parseIntent, resolveIntentFromAggregates } from '../../src/lib/assistant/intents';
import { INITIAL_SETTINGS, INITIAL_SHIFT } from '../../src/data/initialData';
import type { MerchantSnapshot } from '../../src/lib/assistant/types';
import type { Product, Order } from '../../src/types';
import { fixture, now, p, order } from './brainFixture';
import { advanceAction,parseActionJournal,type ActionRecord } from '../../src/lib/assistant/actionJournal';
assert.equal(businessDate('2026-09-16T18:00:00Z'),'2026-09-17');
for(const [q,from,to] of [['omset kemarin','2026-09-16','2026-09-16'],['omset minggu ini','2026-09-14','2026-09-17'],['omset minggu lalu','2026-09-07','2026-09-13'],['omset bulan ini','2026-09-01','2026-09-17'],['omset bulan lalu','2026-08-01','2026-08-31'],['1 sampai 7 September 2026','2026-09-01','2026-09-07']]) {
  const e=parsePeriod(q,now.getTime());const w=reportWindow(e.period,now.getTime(),e);assert.equal(w.startDate,from);assert.equal(w.endDate,to);
}
assert.ok(parsePeriod('tanggal 31 Februari 2026',now.getTime()).clarification);
assert.ok(parsePeriod('omset 2026-09-01 sampai 2026-10-01',now.getTime()).clarification);
assert.ok(parsePeriod('omset 90 hari',now.getTime()).clarification);
assert.equal(parsePeriod('tanggal muda lebih ramai ga',now.getTime()).clarification,undefined);
const monthly=reportAggregates(fixture,{period:'MONTH'});assert.equal(monthly.ordersAnalysed,16);assert.equal(monthly.netSales,1600000);assert.equal(monthly.cogs,640000);assert.equal(monthly.grossMarginPct,60);
const daily=reportAggregates(fixture,{period:'YESTERDAY'});assert.equal(daily.ordersAnalysed,1);assert.equal(daily.revenueTotal,110000);
const response=resolveIntentFromAggregates(parseIntent('omset kemarin',now.getTime()),daily,[],{storeName:'Test',businessSector:'FNB',slotNoun:'Meja',userRole:'ADMIN'});
assert.match(response!.markdown,/kemarin/);assert.doesNotMatch(response!.markdown,/Omset 30 hari/);
const unknownCost={...fixture,orders:[{...fixture.orders[0],items:fixture.orders[0].items.map(i=>({...i,unitCost:undefined}))}]};
assert.equal(reportAggregates(unknownCost,{period:'YESTERDAY'}).costCoveragePct,0);
const empty={...fixture,orders:[]};const b1=ensureDailyInsights(empty,{now});const b2=ensureDailyInsights({...empty,products:[{...p,stock:100}]},{now});
assert.equal(b1.aggregates.stockCritical,1);assert.equal(b2.aggregates.stockCritical,0);
const immutable=JSON.stringify(fixture);const brain=buildBusinessBrain(fixture);assert.equal(JSON.stringify(fixture),immutable);
assert.equal(brain.sales.baselineDays,8);assert.equal(brain.sales.revenue,110000);assert.equal(brain.sales.transactionEffect!+brain.sales.basketEffect!,0);
assert.equal(brain.menu[0].contribution,1800000);assert.equal(brain.menu[0].quadrant,'STAR');
assert.equal(brain.demand[0].days.length,7);assert.ok(brain.demand[0].backtest);assert.equal(brain.demand[0].backtest!.mae,0);
assert.equal(brain.procurement[0].suggestedQty,69);assert.equal(brain.procurement[0].supplier,null);
assert.equal(forecastDemand(p,fixture.orders.slice(0,5),'2026-09-17').method,'INSUFFICIENT');
assert.equal(simulatePrice(10000,4000,12000,100,10)!.delta,120000);assert.equal(simulatePrice(10000,4000,3000,100),null);
assert.equal(nextBestOffers(brain,[],[p]).length,0);
const other=buildBusinessBrain({...fixture,businessId:'other',orders:[],products:[],customers:[]});assert.equal(other.sales.revenue,0);assert.equal(other.procurement.length,0);
for(const sector of ['FNB','RETAIL','LAUNDRY','CARWASH','BARBERSHOP'] as const)assert.ok(buildBusinessBrain({...fixture,businessSector:sector}).sector.title.includes(sector));
console.log('PASS: calendar periods/WIB, exact money, missing HPP, cache refresh, same-weekday decomposition, forecast/backtest, procurement, pricing, sector packs and input immutability');
const action:ActionRecord={id:'test-plan',businessId:fixture.businessId,status:'DRAFT',createdAt:now.toISOString(),
  action:{id:'price-plan',kind:'PRICING',title:'Review price',reason:'test',draft:'No automatic action',metric:'revenue'}};
assert.deepEqual(parseActionJournal('[null,{}]',fixture.businessId),[]);
assert.equal(parseActionJournal(JSON.stringify([action]),'another-business').length,0);
assert.equal(parseActionJournal(JSON.stringify([action]),fixture.businessId).length,1);
assert.throws(()=>advanceAction(action,'DONE',fixture,now,'note'),/INVALID_ACTION_TRANSITION/);
assert.throws(()=>advanceAction(action,'APPROVED',{...fixture,userRole:'CASHIER'},now),/OWNER_APPROVAL_REQUIRED/);
const approved=advanceAction(action,'APPROVED',fixture,now);
assert.throws(()=>advanceAction(approved,'DONE',fixture,now),/Catat tindakan/);
const done=advanceAction(approved,'DONE',fixture,now,'Synthetic test only');
assert.throws(()=>advanceAction(done,'MEASURED',fixture,now),/tujuh hari/);
assert.equal(advanceAction(done,'MEASURED',fixture,new Date(now.getTime()+7*DAY)).status,'MEASURED');
assert.equal(reportAggregates({...fixture,orders:[{...fixture.orders[0],paymentStatus:'PENDING'}]},{period:'LAST_30'}).revenueTotal,0);
console.log('PASS: owner approval transitions, corrupted/cross-business draft isolation, 7-day gate and unpaid exclusion');
